using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WhoIsTheDaddy : MonoBehaviour
{
    private GameObject player;

    void Awake()
    {
        player = GameObject.FindGameObjectWithTag("Player");
    }


    private void OnCollisionEnter(Collision collision)
    {
        if(collision.gameObject == player)
        {
            player.transform.parent = this.transform;
        }
    }

    private void OnCollisionExit(Collision collision)
    {
        if(collision.gameObject == player)
        {
            player.transform.parent = null;
        }
    }



}
